@extends('frontend.layouts.app')

@section('main-content')
    <section class="terms">
        <div class="container">
            <h3> {{ $page->title }} </h3>

            <article>
                <!-- {!! $page->description !!} -->
                <strong>PRIVACY POLICY</strong>


Our Privacy Policy was last updated on 12th August ‘24
<strong>GENERAL</strong>
<br>
The website https://woich.in/ and the mobile application, if any (collectively be referred to as “the Platform”).
<br>
We value your privacy! This Privacy Policy (“Privacy Policy”) describes our policies and procedures on the collection, use, disclosure, processing, transfer, and storage of the information provided to us when you use the Platform and/or services and tells you about your privacy rights and how the law protects you. 

<br>
Your privacy is extremely important to us. At the Platform, we believe in being absolutely transparent about our Privacy Policy so that you can focus on availing the services provided by the Platform without worrying. We maintain complete confidentiality of all your personal information collected by us on the Platform.

<br>
Please be informed  we shall not use the your information in any manner except as provided under this Privacy Policy and that by using, browsing, accessing, or purchasing on the Platform you agree to be bound by the terms of this Privacy Policy and consent to the collection, storage, possession, dealing, handling, sharing, disclosure or transfer of your information in accordance with the terms of the Privacy Policy. 

This document is an electronic record and is governed by the provisions under the Information Technology Act, 2000 and rules and amendments made thereunder as may be applicable. This electronic record is generated by a computer system and does not require any physical or digital signatures.
<br>

To know your privacy rights, you are advised to read this Privacy Policy carefully before accessing the Platform.

<br>
You may at anytime withdraw your consent for collection and use of your information including Personal Information (defined hereinafter) or Sensitive Personal Data or Information, by way of writing to us on _______. However, please note that if you withdraw your consent, we may no longer be able to provide you with the corresponding service for which you have withdrawn your consent. It is hereby clarified that your decision to withdraw your consent will not affect the processing of Personal Information based on your previous consent prior to the withdrawal.

<br>
Platform is not directed towards minors. We do not knowingly collect Personal Information from any User who is under 18 (Eighteen) years. If we are made aware that we have collected the Personal Information of a person below the age of 18 (Eighteen) years, we will take steps to delete the information within a reasonable time frame. If a parent or guardian becomes aware that his or her child has provided his/ her information on the Platform without their consent, he or she shall contact us for the deletion of such information. In the event, where in contravention to the Privacy Policy and Terms, a person below the age of 18 (Eighteen) uses the services, we shall not be held liable or responsible for any damage or injury suffered by such person.
<br>
<strong>
WHAT DATA WE COLLECT </strong>

<br>
We may collect a variety of information from you, including your name, password, mailing and residential address, phone number, email address, social media handles, date of birth, gender description of your business and contact preferences, including any other usage and interaction details. We may collect such information which when combined with other pieces of information available with us could reasonably allow you to be identified (“Personal Information”). 


You may be asked to provide your information anytime you visit, access, use or browse the Platform. We may share information and use it in a manner consistent with the provisions of this Privacy Policy. We may also combine it with other information to provide and improve our Platform, products, services, content and advertising. 
<br>

We may also collect, receive, process or store certain sensitive personal data or information consisting of, but not limited to:
<br>

Password;

<br>
Financial information such as bank account or credit card or debit card or other payment instrument details; and
<br>
Any detail relating to the above Personal Information categories as provided to us for providing service, processing, stored or processed under lawful contract or otherwise.
(Collectively, referred to as “Sensitive Personal Data or Information”). 
<br>
Technical Information about You: We automatically collect certain information from You when You use the Platform, including your IP address (static or dynamic), location, other unique device identifiers, your browser type, browser language, the URL of the website which you may have used to reach our Platform, other browser history, search terms, number of clicks, domain names, and cookies (defined below), landing pages, pages viewed and the order of those pages, the amount of time spent on particular pages, the date and time,etc.
From your device: Type of device, advertising identifier, device identifiers (such as IMEI), operating system and version, carrier, language settings, geo-location, network type (2G,3G,4G,WiFi) screen resolution, etc.
<br>
Messages: When you use our Platform to communicate, we receive and collect the messages you may send or receive on the Platform, and any other content you may upload or share on the Platform.
<br>
Cookies: We use cookies, small text files that uniquely identify your browser and enable Us to recognize the information you have consented to give us, to store certain types of information each time you visit any page on our Platform. These cookies do not contain any personal information and you may choose what cookies you allow by managing your cookies settings on your browser. This will allow you to delete your browser cookies or disable them entirely, however, if you choose to disable all cookies, it will affect your overall experience with our Platform and it may make parts of our Platform non-functional or inaccessible to you in such cases. Therefore, we recommend that you enable cookies for our Platform. The cookies we collect are mainly used to serve advertising banners to you and in doing so we may use the services of third parties. Such third-party service providers do not know the name, phone number, address, email address, or any personal information about you, and no personal information is collected or used in this process.
<br>
<strong>USAGE OF DATA COLLECTED </strong>
<br>
3.1	We may collect, use or process your information including Personal Information and Sensitive Personal Data or Information for the following purposes: 
<br>
3.1.1	For creating and giving you access to your account on the Platform.
<br>
3.1.2	To develop, deliver, process and improve our Platform, products, services, content in order to personalize and improve your experience.
<br>
3.1.3	To inform you about our products, services, offers, updates, upcoming events, including providing you information in relation to order confirmations, invoices, technical notices, security alerts. 
<br>
3.1.4	For internal analytical and research purposes such as auditing, data analysis and research to improve our products, services and customer communications.
<br>
3.1.5	To meet any legal or regulatory requirement or comply with a request from any governmental or judicial authority. 
<br>
3.1.6	To resolve any request, dispute, grievance or complaint raised by you in relation to your use of the Platform. 
<br>
3.1.7	To detect or monitor any fraudulent or illegal activity on the Platform.
<br>
<strong>4.	DISCLOSURE OF INFORMATION COLLECTED</strong>
<br>
We may, from time to time, be required to disclose the information collected from you in following situations:
<br>
4.1.1	Third party service providers, to monitor and analyse the use of our service, for payment processing, to contact you;
4.1.2	Law or judicial authority, deem it necessary in order to protect our rights or the rights of other Users, to prevent harm to persons or property, to fight fraud and credit risk;
4.1.3	Business transfers, as a part of reorganization or a sale of the assets, division or transfer of a part or whole of us;
4.1.4	Business Partner, to offer you certain products, services and/or promotions;
4.1.5	Other Purpose, with your consent
<br>

<strong>5.	SECURITY</strong>
<br>
5.1	Your information is contained within secured networks and is only accessible by a limited number of authorized persons who have access rights to such systems or otherwise require such information for the purposes provided in this Privacy Policy. These authorized persons are also under an obligation to keep such information confidential.
<br>
5.3	Although we make best possible efforts to transmit and store all the information provided by you in a secure operating environment that is not open to public, you understand and acknowledge that there is no such thing as complete security and we do not guarantee that there will be no unintended disclosures of any information and potential security breaches. You agree not to hold us responsible for any breach of security or for any action of any third parties that receive your Personal Information or events that are beyond our reasonable control including, acts of government, computer hacking, unauthorized access to computer data and storage device, computer crashes, breach of security and encryption, etc.
<br>
<strong>6.	COOKIES POLICY</strong>
<br>
6.1	Due to the communications standards on the Internet, when you visits, access or browse the 
Platform, we automatically receive the uniform resource locator of the site from which such you visit, access or browse the Platform, details of the website you visit on leaving the Platform, the internet protocol (“IP”) address of each user’s computer operating system, type of web browser the user is using, email patterns, and the name of the user’s internet service provider. This information is used solely to analyse overall user trends and to help us improve our services. Please note that the link between the user’s IP address and the user’s personally identifiable information is not shared with third parties without such user’s permission or except when required by law or to provide or facilitate the user with the services. 
<br>
6.2	Please note that cookies don't allow us to gain control of your computer in any way. They are strictly used to monitor which pages you find useful and which you do not so that we can provide a better experience for you.
<br>
6.3	If you want to disable cookies, you can do it by accessing the settings of your internet browser.

<br>
<strong>7.	OPT-OUT POLICY</strong>
<br>
You have the right to opt-out of the sale of your Personal Information, Sensitive Personal Data or Information. Once We receive and confirm a verifiable consumer request from You, we will stop processing your information. To exercise Your right to opt-out, please contact us at ________________. 	
<br>
<strong>8.	RETENTION OF INFORMATION</strong> 

We will retain your information and any data for the period necessary to fulfil the purposes outlined in this Privacy Policy unless a longer retention period is required or permitted under the applicable law. 
<br>
<strong>9. 	MODIFICATION</strong>
<br>

We reserve the right to amend this Privacy Policy at any time. The Privacy Policy, as and when modified, shall be updated on the Platform. We encourage you to review this Privacy Policy whenever you visit our Platform to understand how your Personal Information is used.
<br>
<strong>10	GRIEVANCE REDRESSAL</strong>
<br>
In case, you have any questions, grievance or complaints about this Privacy Policy, or the Platform, you may contact us at ___________
<br>
<strong>11.	GOVERNING LAW</strong>
<br>
The terms of this Privacy Policy shall be governed and construed in accordance with the laws of India. Any dispute regarding or arising out of this Privacy Policy shall be subject to the exclusive jurisdiction of the courts in Mumbai, Maharashtra.
<br>
<strong>12.	SEVERABILITY 	</strong>
<br>
Whenever possible, each section of this Privacy Policy shall be interpreted in a manner so as to be valid under applicable law. However, in the event any provision is held to be prohibited or invalid, such provision shall be ineffective only to the extent of such prohibition or invalidity, without invalidating the remainder of such provision or other remaining provisions of this Privacy Policy.
<br>
<strong>13.	FEEDBACK OR CONCERN</strong> 
<br>
If the User has any concerns, feedback, review or any request, the User is free to contact the at __________.

****


            </article>
        </div>
    </section>
@endsection
