@extends('frontend.layouts.app')

@section('main-content')
    <section class="terms">
        <div class="container">
            <h3> {{ $page->title }} </h3>

            <article style="font-size: 12px;">
                <!-- {!! $page->description !!} -->

<strong>
TERMS OF SERVICE</strong>
<br>
Our Terms of Service was last updated on August 12, 2024
<br>
Welcome to Woich!
<br>
The website https://woich.in/ and the mobile application, if any (collectively be referred to as “ <strong>the Platform</strong>”).
<br>
The terms and conditions as set out hereinbelow <strong>(“Terms”)</strong>  constitute an agreement between the Platform ( <strong>“we”</strong>, <strong>“us”</strong>, <strong>“our”</strong>) and any natural or legal person (including any legal heirs, administrators or successors) who accesses, offers  services, and/or uses the Platform in any manner (referred to as <strong>“you”</strong>, <strong>“your”</strong>, <strong>“User”</strong> ), or uses any current or future service or functionality or offer made available on the Platform (“Service(s)”), as updated from time to time.
<br>
By using or accessing the Platform, you signify your agreement to be bound by these Terms and any other applicable policies as uploaded on the Platform (collectively called <strong>“Platform Policies”</strong> ) along with any schedule(s), addendum(s), annexures(s), Statement Of Work(s) (SOW), Standard Operating Process(es) (SOP) as may be entered by you or provided to you or as may be amended from time to time, which shall constitute your binding agreement, with us (hereinafter <strong>“Agreement”</strong> ). 
<br>
If you do not agree with any of these Terms or Platform Policies, please do not use the Platform. If you have any questions about these Terms, please contact us at maasa.ventures@gmail.com for assistance.
<br>
This document is an electronic record and is governed by the provisions under the Information Technology Act, 2000 and rules and amendments made thereunder as may be applicable. This electronic record is generated by a computer system and does not require any physical or digital signatures.
<br>
This document is published in accordance with the provisions of Rule 3(1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and terms & conditions for access or usage of the Platform. 
<br>
We and you are hereinafter individually referred to as <strong>“Party”</strong> and collectively as <strong>“Parties”</strong>.
<br>
<strong>1. GENERAL</strong>
<br>
These Terms as set out herein specifically govern your access and use of the Platform which provides a forum for Sellers to inter alia offer their business and thereupon list their products/goods/consumables/services ( <strong>“Products”</strong> ) on the Platform along with other relevant details for an end-user ( <strong>“Buyers”</strong> ) to view, avail, connect to the Sellers for buying their Products via the Platform.
<br>

We enable transactions on the Platform for participating entrepreneurs/stores/merchants/sellers/service providers/ restaurants etc ( <strong>“Sellers”</strong> ) to offer their lawful business(es) in the categories, including but not limited to food and beverages, home décor, gifting articles, education, fitness and any other approved business, products or services under the applicable laws.
<br>
We authorise you to browse, view, use and access the Platform solely for Services offered on the Platform. 
<br>
By accepting this Agreement, you affirm that you are 18 (Eighteen) years of age or above and are fully competent to enter into this Agreement, and to abide by and comply with this Agreement. If you are below 18 (eighteen) years of age, it is assumed that you are using/browsing the Platform under the supervision of a parent or legal guardian and that such parent or legal guardian has read these Terms and agrees with the same, including terms of purchase of Service(s) on your behalf. In the event we are made aware that a User is under the age of 18 years and has been using/browsing the Platform without the supervision of their parent or legal guardian, then in such case, we reserve the right to deactivate such account without further notice. Further, if you are using the Services on behalf of a company or organisation, you represent that you have authority to act on behalf of such entity, and that such entity accepts these Terms.
<br>
<strong>2. REGISTRATION OF ACCOUNT</strong>
Registration is a one-time process. In order to purchase Products on the Platform, you must register on the Platform account (<strong>“Account”</strong> ). To complete your Account registration, you must provide us with your full name, email address, phone number, password and any other information indicated as required.

<br>
You acknowledge that we will use the email address and phone number you provide on opening an Account or as updated by you from time to time as the primary method for communication with you ( <strong>“Primary Contact”</strong> ). You must monitor the Primary Contact you provide to us and your Primary Contact must be capable of both sending and receiving messages.
<br>
<strong>
3. USER ACCOUNT OBLIGATIONS</strong>
You are solely authorized to operate the Account created by you. Consequently, it is your responsibility to maintain the confidentiality of the login credentials of your Account on the Platform and for restricting access to your computer/mobile/other similar devices to prevent unauthorized access to your Account. You shall remain solely liable for all the actions/inactions undertaken through your Account.
<br>
You agree that if you provide any information that is untrue, inaccurate, not current or incomplete or we have reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, or not in accordance with the these Terms, we shall have the right to indefinitely suspend or terminate or block access of your Account on the Platform and refuse to provide you with access to the Platform.
<br>
You will: (a) immediately inform us of any unauthorized use of the account or any other security breach; and (b) ensure that you log out of your Account at the end of each session. If you share or allow others to have access to your Account on the Platform, or otherwise, they will be able to view and access your Account information. You shall be solely liable and responsible for all the activities undertaken under your Account, and any consequences arising therefrom.
<br>
You agree not to reproduce, duplicate, copy, sell, resell or exploit, work around, bypass, or circumvent any of the technical limitations any portion of the Service, decompile, disassemble or otherwise reverse engineer use of the Services, or access to the Services without our express written permission, not to access the Services or monitor any material or information from the Services using any robot, spider, scraper, or other automated means

<br>
You understand that your Materials may be transferred unencrypted and involve (a) transmissions over various networks; and (b) changes to conform and adapt to technical requirements of connecting networks or devices. <strong>“Materials”</strong> means your trademarks, copyright content, any Products or services you sell or offer to sell through the Services (including description and price), and any photos, images, videos, graphics, written content, audio files, code, information, or other data provided or made available by you or your affiliates to us or our affiliates.
<br>
<strong>4. ONLINE PLATFORM FOR TRANSACTION AND COMMUNICATION
</strong>
You agree, understand and acknowledge that, this is an online platform that enables you to explore, discover the Sellers of the Products listed on the Platform and thereupon make purchases on the Platform. You further agree and acknowledge that the Platform is only a facilitator and is not and cannot be a party to, or control in any manner, any transactions on the Platform. Accordingly, the contract of sale of Products on the Platform shall be a strictly bipartite contract between Seller and the Buyer independently.
For purpose of clarifications, the Platform is a platform that Buyers and Sellers utilize to meet and interact with one another for conducting their transactions. The Platform is not and cannot be, a party to or control in any manner any transaction between the Platform's users i.e. Buyers and Seller.
<br>
<strong>5. MODIFICATION</strong>
We reserve the right to amend these Terms at any time. The Terms, as and when modified, shall be updated on the Platform. We encourage you to review these Terms whenever you visit our Platform.
<br>
We may be required to make changes that materially adversely affect your use of the Services or your rights under these Terms at any time and with immediate effect (i) for legal, regulatory, fraud and abuse prevention, or security reasons; or (ii) to restrict products, services or activities that we deem unsafe, inappropriate, or offensive.
<br>
Every time you wish to use our Platform, please check these Terms to ensure you understand the terms and conditions that apply at that time. Further, please note that we reserve the right to either change the format and/or the content of the Platform or suspend the operation(s) of the Platform for support or maintenance work, at any time.
<br>
Any changes to the Terms will be effective immediately upon posting of such updated terms at this location. We may, in certain circumstances, also require you to provide your consent to the updated Terms in a specified manner prior to any further use of the the Platform. Your continued access to or use of the Services after we post such updated Terms, constitutes your acceptance of the changes and consent to be bound by these Terms, as amended. If you do not agree to the amended Terms, you must stop accessing the Platform.
<br>
<strong>6. COMMUNICATION AND UNSUBSCRIPTION</strong>
By accepting these Terms, you also accept to receive the news, updates, offers/ campaign related SMS emails, notifications and whatsapp communication to the mobile phone number and email address provided by you. By accessing and using the Platform and/ or verifying your contact number / email address with us; by accepting these Terms; by accepting or receiving and not unsubscribing expressly on the consent  availed by us from you via SMS, Email-s, Voice calls, IVR (Interactive Voice Response) or any other modes and methods of communication, you explicitly consent to receive such communications (through call, SMS, email or other digital and electronic means) from us and/or our authorized representatives regarding any new services or offerings, even if your contact number is registered under the DND/NCPR list under the Telecom Commercial Communications Customer Preference Regulations, 2018.
<br>
The effectiveness, clarity, and timeliness of communications are influenced by multiple factors. We assume no responsibility for non-delivery, delayed delivery, or any distortion of communication in any manner whatsoever. You can unsubscribe/ opt-out from receiving marketing/ promotional communications, newsletters and other notifications from us at any time by following the instructions set out in such communications or writing to us on maasa.ventures@gmail.com 
<br>
<strong>7. SELLER OBLIGATIONS</strong>
You agree to provide true, accurate, up to date and complete information while signing up on the Platform or for any other purpose when prompted or requested to do so on the Platform.
<br>
You agree that when you use the Platform, you are involved in the transmission of personal information including but not limited to Account information (collectively "SPI") which falls within the ambit of the Information Technology (Reasonable Security practices and procedures and sensitive personal data or information) Rules, 2011 and any other law that may be applicable from time to time. However, you acknowledge that we will not be liable for any disclosure of your SPI as a result of an error in transmission or unauthorized actions of third parties.
<br>
For availing the Service(s), you may be required to use certain devices, software, and data connections, which we otherwise do not supply. You are responsible for all carrier data plan and other fees and taxes associated with your use of our Services. We may charge you for our Services, including applicable taxes. 
<br>
You are prohibited from misrepresenting your identity and agree not to represent yourself as another User or login / register using the identity of any other person. You are responsible to maintain and promptly update the information on the Platform.
<br>
You acknowledge and agree to provide correct public-facing information including but not limited to pricing information, contact details, order fulfilment timelines etc and comply with all applicable legal, regulatory and industry standards vis-à-vis your Sales Channel hosted by the Platform. 
<br>
You acknowledge and agree that any contract of sale made for your Products, is directly between you and the Buyer. You are the seller on record for all items you sell by using the Services. The Platform shall not be responsible for providing or helping you with any legal, regulatory or industry mandates that are applicable to the operation of your business.
<br>
You are responsible for the creation and operation of your Account, your Products that you may sell/offer to sale via Platform, and all aspects of the transactions between you and Buyer. This includes, but is not limited to, authorizing the charge to the Buyer in respect of the Buyer’s purchase, refunds, returns, fulfilling any sales or customer service, fraudulent transactions, required legal disclosures, regulatory compliance, alleged or actual violation of applicable laws, or your breach of these Terms. We do not have any control or do not determine or advise in any way or involve itself in the offering or acceptance of such commercial/contractual terms between you and Buyer. The price of the Products offered by you are solely determined by you itself, we have no role to play in such determination of price in any way whatsoever.
<br>
The Platform is operating as an online intermediary and assumes the role of facilitator and does not at any point of time during any transaction between the Buyer and Seller on the Platform, come into or take possession of any of the Products offered by Seller. We are only providing a platform for communication, and it is agreed that the contract for sale of any of the Products shall be a strictly bipartite contract between the Seller and the Buyer. At no time shall the Platform hold any right, title or interest over the Products, nor shall the Platform have any obligations or liabilities in respect of such agreement of sale entered into between Buyer and Seller.
<br>
You may not use the Services for any illegal or unauthorized purpose nor may you, in the use of the Services, violate any laws in your jurisdiction or the laws applicable to you. You will be solely responsible to comply with all applicable laws, rules and regulations (including but not limited to obtaining and complying with the requirements of any license or permit that may be necessary to offer your Product) in your use of the Service and your performance of obligations under these Terms.
<br>
You agree to indemnify the Platform for any and all claims, losses, damages or fines incurred by the Platform due to your use of the Platform (including but not limited to, your breach of any applicable laws or regulations). We will  not be responsible for unsatisfactory or non-performance of services or damages or delays caused by you to the Buyer, as a result of any shortcoming at your own end in fulfilling the end-customer’s expectations.
<br>
You may list and provide the details of the Products offered for sale to the end-customer as a User on the Platform, however you shall not be permitted to sell any product that fall under the list of banned items or are otherwise prohibited for sale under applicable law.
<br>
You agree and undertake that you are legally permitted to sell the Products listed for sale on the Platform. Listings may only include text descriptions, graphics and pictures that describe your Products for sale. 
<br>
You hereby agree and undertake that descriptions, images, and other content pertaining to the Products is complete and accurate, and corresponds directly with the appearance, nature, quality, purpose and other features of such Products.
<br>
The listing description of the Products must not be misleading and must describe the actual condition of the Product. If the Product description does not match the actual Product, you agree to refund any amounts that you may have received from the Buyer.
<br>
You shall not abuse or misuse the Platform or engage in any activity which violates these Terms. Further, you shall not engage in any activity that may have a detrimental effect or may create an adverse impact on the Platform’s business or goodwill. In any such case, we may suspend your account or permanently debar you from accessing the Platform.
<br>
You hereby agree in not engaging in any unfair trade practice viz manipulating price of Products or imposing unjustified price.
<br>
You hereby agree to be solely responsible for any dispute and liability that may be raised by end-customer relating to the quality, quantity, merchantability of Products or services sold by you via the Platform.
<br>
We respect the intellectual property of others and expects you to do the same. We reserve the right to remove content alleged to be infringing any other person’s intellectual property rights, without prior notice, at our sole discretion, and without any liability to you. We will respond to notices of alleged infringement that comply with applicable law and are properly provided to us. If you believe that your content has been copied in a way that constitutes copyright infringement, please report this at maasa.ventures@gmail.com 
<br>
You confirm that there is no action, suit or proceeding pending against you or to your knowledge, threatened in any court or by or before any other authority which would prohibit your entering into or performing obligations under this Agreement.
<br>
You represent and warrant that you are not subject to sanctions or otherwise designated on any list of prohibited or restricted parties or owned or controlled by such a party, including but not limited to the lists maintained by the United Nations Security Council, the US Government (e.g., the US Department of Treasury's Specially Designated Nationals list and Foreign Sanctions Evaders list and the US Department of Commerce’s Entity List), the European Union or its member states, or other applicable government authority. It is essential that you strictly comply with all relevant trade laws, export control laws. Any use of our Services for purposes that contravene the stipulations of pertinent trade laws is expressly forbidden.
<br>
You confirm that you shall not transfer your Account and shall not assign any rights and obligations under this Agreement to any third party without our specific prior written permission.
<br>
<strong>8. PAYMENT OF FEES </strong>
The Platform may charge the Seller for the Service(s) provided on the Platform (“Service Fee”). The Service Fee shall be discussed mutually between the Platform and the Seller and memorialised in writing upon signing a service order/addendum.   
<br>
We do not provide refunds for our Services, except as required by applicable law.
<br>
Fees shall be exclusive of any applicable statutory taxes, levies, fees or charges, imposed by the government as per the applicable law, now in force or enacted in future (<strong>“Taxes”</strong> ). 
<br>
You are solely responsible for determining, collecting, withholding, reporting, and remitting applicable taxes, duties, fees, surcharges and additional charges that arise from or as a result of any sale to Buyer. 
<br>
While availing any of the payment method/s available on the Platform, we will not be responsible or assume any liability, whatsoever in respect of any loss or damage arising directly or indirectly to you due to:
Lack of authorization for any transaction;
Exceeding the preset limit mutually agreed by you and between you and the bank;
Any payment issues arising out of the transaction; or
Decline of transaction for any other reason.
<br>
You acknowledge and agree that you shall not use the details of credit card/debit card/net-banking or any other payment instrument which is not lawfully owned by you.
<br>
All payments made for the Services on the Platform shall be made in Indian Rupees (INR).
<br>
Your relationship with the Platform is on a principal-to-principal basis and by accepting these Terms, you agree that the Platform is an independent contractor for all purposes and does not have control of or liability for the Products or services that are listed via the Platform. We do not guarantee the identity of any end-customer, nor does it ensure that an end-customer or a Seller will complete a transaction.
<br>
<strong>9. TAX COMPLIANCES </strong>
<strong>Tax Deducted at Source (TDS)</strong>
In case if the Platform is providing Services in the form of an e-commerce marketplace, it shall deduct TDS as per Section 194O of the Income Tax Act, 1961 on gross transaction value of the Product, as per the applicable rate in force; and
In all other case, Seller shall pay the TDS on Fees as applicable, to the government on behalf of the Platform & certificate for the same will be shared periodically (within 45 days from the end of every quarter) to the Platform, for reimbursement of the same. 
<br>
<strong>Goods and Service Tax (GST)</strong>
You agree that, in case if the GST regime applies to you, then you shall require registration in accordance with the applicable statute and to remain compliant at all times with such statute. You agree to share the registration number, GST certificate or other unique ID/ number and GST registered address, with the Platform, whenever demanded, in order to ensure compliance.
Seller shall undertake the responsibility for the periodic filing of taxes to the statutory tax departments as mandated under the applicable law, from time to time. 
You acknowledge that for all the invoice(s) raised by the Seller upon the Buyer, Seller would be responsible for collecting GST directly from the Buyer and shall be depositing the same to the government.  
<br>
<strong>10. TERM  </strong>
Term. The Term of this Agreement shall come into force and effect from the date you complete your Account registration for a Service on the Platform and shall continue unless otherwise terminated by either or both Parties in accordance with Clause 11 (Breach and Termination).  
You may cancel your Account and terminate this Agreement at any time, by contacting us at maasa.ventures@gmail.com and then following the specific instructions indicated to you by us. 
<br>
<strong>11. BREACH AND TERMINATION</strong>
Without limiting other remedies that the Platform may at its discretion take such action as it deems fit, limit your activity on the Platform, immediately remove your information, forthwith temporarily/indefinitely suspend or terminate or block your Account, and/or refuse to provide you with access to the Platform or initiate any legal action it may deem fit, particularly in the event: 
You have committed a material breach of these Terms or the documents it incorporates herein by reference and have failed to remedy the same within a period of 15 (fifteen) days from the date of receipt of a notice of breach from us; 
Your misuse your Account; 
the Platform believes that your actions may cause legal liability to the Platform, other users or yourself;
You fail to make the respective payment due to the Platform, despite repeated reminders and notifications, for more than 2 (two) consecutive months; 
You do not possess / produce the requisite legal or compliance document(s), license(s), certification(s), registration(s), required to sell or offer certain Products / services on the Platform;
the Platform suspects that you (by conviction, settlement, insurance or escrow investigation, or otherwise) have engaged in fraudulent or criminal activity in connection with the use of the Services;
You have filed a petition for bankruptcy or insolvency, or are unable to pay your debts, or are subject to a petition presented before a court for winding up.
<br>
In case your access or use of the Services is terminated for any of the reasons mentioned hereinabove, Platform and its personnel shall not be liable for any damages, losses, direct, indirect, immediate or remote, interests or claims that may occur to you or to any third party. 
<br>
You agree and acknowledge that we, in our sole discretion, without prior notification or intimation, may terminate your access, to all or part of the Platform, or cease to provide accessibility to the Platform, for reasons including but not limited to:
In response to the requests of law enforcement agencies or other government institutions;
In response to your own request;
Unforeseeable technical issues;
Occurrence of an event outside our control.
<br>
All your obligations and liabilities incurred prior to the termination date shall survive the termination of this Agreement for all purposes.
<br>
<strong>Consequences of Termination</strong>. Upon such termination of this Agreement by either Party for any reason:
We shall revoke your access to the Account and take custody or control of the same, remove the links, discontinue display of your Products on the Platform;
We shall enforce that you cease to use and return any/all intellectual property, confidential information (if any) that belongs to us;
Both the Parties shall endeavour to perform respective obligations up to the date of termination in business-like manner;
If there are any outstanding Service Fees owed by you at the date of termination of the Service, you will receive one final invoice via email, which you must settle immediately within 7 (seven) business days from the date of such invoice;
Any outstanding balance owed to the Platform for your use of the Services until the effective date of such termination will immediately become due and payable; and
Both Parties will be regarded as discharged from any further obligations upon expiry of date of termination under his Agreement, only after due payment of Service Fees by you to the Platform.
<br>
<strong>12. REPRESENTATIONS & COVENANTS</strong>
Seller represents and warrants as follows:
Complete responsibility of the Product and all liability related to the Products and services shall solely vest with the Seller and that Seller shall be solely responsible to the Buyer for the sale or offering of its Products/services including but not limited to its timely dispatch/provision to the end-customer; 
The Products/services listed by Seller through the Platform, are owned by the Seller or are duly licensed to the Seller since the Platform is merely a facilitator providing its listing services to enable online sale or offering of the Seller’s Products/services;
The Products shall be in a merchantable condition and such Products shall conform to the quality standards prescribed under applicable law, if any.
Any information provided by the Seller, together with Products concerning quality, purpose, user’s guide and operating instructions, descriptions, accompanying certificates or any other papers for the Products are correct, not misleading and complete in all material respects and end-customers shall have the unconditional right to use the user’s guide, operating instructions, descriptions and other papers / images.
The Products are genuine, defect free and not counterfeits.
<br>
<strong>Seller Covenants.</strong> Seller covenants and undertakes that (a) they shall not provide any information to the Platform, which is untrue, inaccurate, not current, or incomplete; (b) they shall maintain the secrecy of the login credentials to the Account provided by the Platform, at all times, and upon breach of such secrecy, immediately intimate the Platform (by way of email at maasa.ventures@gmail.com) to block such Account; (c) they shall make due payment of Service Fees to Platform; (d) they shall refrain from any misuse, damage, destruction or any form of unauthorized use of the Services on the Platform at all times, during and after the Term.
<br>
<strong>13. DISCLAIMER OF WARRANTIES, INACCURACIES & ERRORS</strong>
The Platform may be under constant upgrades, and some functions and features may not be fully operational.

Due to the vagaries that can occur in the electronic distribution of information and due to the limitations inherent in providing information obtained from multiple sources, there may be delays, omissions, or inaccuracies in the content provided on the Platform or delay or errors in functionality of the Platform. As a result, we do not represent that the information posted is correct in every case.
<br>
We expressly disclaim all liabilities that may arise as a consequence of any unauthorized use of credit/ debit cards by a User or end-customer or a Buyer.
<br>
We disclaim all liability with respect to Products and services offered by the Seller via the Platform. 

We do not warrant that the Services will be uninterrupted, timely, secure, or error-free.

We do not warrant that the results that may be obtained from the use of the Services will be accurate or reliable.

We are not responsible for any of your tax obligations or liabilities related to the use of the Platform’s Services.

We shall not be liable to you or anyone else for any losses or injury arising out of or relating to the information provided on the Platform. In no event will we or our personnel be liable to you or any third party for any decision made, or action taken by your reliance on the content contained on the Platform.
<br>
In no event will we be liable for any damages (including, without limitation, direct, indirect, incidental, special, consequential or exemplary damages, damages arising from personal injury/wrongful death, and damages resulting from lost profits, lost data or business interruption), resulting from any services provided by any third party or merchant accessed through the Platform, whether based on warranty, contract, tort, or any other legal theory and whether or not we are advised of the possibility of such damages.
<br>
Further, we specifically disclaim, any and all warranties, and you agree (a) we are not responsible or liable for the Product design, its functions and condition, manufacturing and selling and financial obligations, warranties, guarantees, whatsoever; (b) we do not warrant and assumes no responsibility for the accuracy of the Product description or other content on the Platform or its completeness and reliability.
<br>
We do not assume any responsibility for the proceedings undertaken by an aggrieved end-customer against you in the event of your non-adherence with the applicable law and any data protection laws and obligations. However, in the event of a complaint from an end-customer, you shall be obligated to answer queries on the non-adherence to the applicable law including but not limited to the Legal Metrology Act, failing which we can temporarily/indefinitely suspend/terminate/block/with-hold your Account, at our own discretion.
<strong>
<br>
THE PLATFORM AND THE SERVICES ARE PROVIDED TO YOU ON AN “AS IS” AND “WHERE-IS'' BASIS, WITHOUT ANY REPRESENTATIONS OR WARRANTIES. WE, FOR OURSELVES AND ANY THIRD-PARTY PROVIDING MATERIALS, SERVICES, OR CONTENT TO THIS WEBSITE, MAKE NO REPRESENTATIONS OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY OR OTHERWISE OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON INFRINGEMENT OF THIRD-PARTY RIGHTS, WITH RESPECT TO THE PLATFORM, THE INFORMATION OR ANY PRODUCTS OR SERVICES TO WHICH THE INFORMATION REFERS. WE WILL NOT BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY DAMAGES OF ANY KIND, INCLUDING BUT NOT LIMITED TO, DIRECT, INDIRECT, INCIDENTAL, CONSEQUENTIAL OR PUNITIVE DAMAGES, ARISING FROM OR CONNECTED WITH THE SITE, INCLUDING BUT NOT LIMITED TO, YOUR USE OF THE PLATFORM OR YOUR INABILITY TO USE THE PLATFORM, EVEN IF WE HAVE PREVIOUSLY BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
</strong>
<br>
<strong>14. INTELLECTUAL PROPERTY RIGHTS</strong>
Each Party shall, solely and exclusively own worldwide, in perpetuity, including renewal and extension periods, their respective Intellectual Property and nothing in this Agreement shall be construed as conferring ownership of the Intellectual Property rights to other Party in any manner whatsoever.

<br>
Upon termination of this Agreement, all rights relating to Platform’s proprietary rights, along with modifications thereto, shall continue to vest with the Platform and you shall not have any right whatsoever, over such Intellectual Property.

<br>
You shall not reverse assemble or reverse compile or reverse engineer in any manner whatsoever or directly or indirectly allow or cause a third-party to reverse assemble or reverse compile or reverse engineer in any manner whatsoever the whole or any part of the Platform’s Proprietary Rights.
<br>
<strong>15. CONFIDENTIALITY</strong>
During the Term of this Agreement, a Party (<strong>“Receiving Party”</strong> ) may receive or have access to certain Confidential Information belonging and/or relating to the other Party and its affiliates (<strong>“Disclosing Party”</strong> ).

The Receiving Party shall keep Confidential Information of the Disclosing Party in confidence. The Receiving Party shall use commercial reasonable and necessary safety measures and steps to maintain the confidentiality and secrecy of Disclosing Party’s Confidential Information from public disclosure, and the Receiving Party shall, at all times, maintain appropriate measures to protect the security and integrity of the Disclosing Party’s Confidential Information. The Receiving Party shall not, without the Disclosing Party’s prior written consent, divulge any of its Confidential Information to any third-party other than the Receiving Party’s officers, employees, agents, affiliates or representatives who have a need to know for the purposes of this Agreement, ensuring that they comply with same level of obligation in maintaining the Confidentiality under this Agreement.
<br>
<strong>Exceptions:</strong> The aforesaid confidentiality obligations shall impose no obligation on the Receiving Party with respect to any portion of Confidential Information which:
Was at the time received or which thereafter becomes, through no act or failure on the part of the Receiving Party, generally known or available to the public;
Is at the time of receipt, known to the Receiving Party as evidenced by written documentation then rightfully in the possession of either Party;
Was already acquired by the Receiving Party from a third-party who does not thereby breach an obligation of confidentiality to the Disclosing Party and who discloses it to the Receiving Party in good faith;
 Is developed by the Receiving Party without use of the Disclosing Party’s Confidential Information in such development; and
Has been disclosed pursuant to the requirements of applicable law, any Governmental Authority, provided however, that the Disclosing Party shall have been given a reasonable opportunity to resist disclosure and/or to obtain a suitable protective order.

Neither Party shall disclose this Agreement and the term of this Agreement to any other person without the consent of the other Party. 

The Parties acknowledge and understand that any disclosure or misappropriation of any of the Confidential Information in violation of this Agreement, may cause irreparable harm to the non-disclosing Party, the amount of which may be difficult to ascertain. Without prejudice to any other rights available to the Disclosing Party under this Agreement or otherwise, Disclosing Party shall have the right to apply to a court of competent jurisdiction for specific performance and/or an order restraining and enjoining any such further disclosure or breach and for such other relief as such non-disclosing Party shall deem appropriate. To clarify, such right shall be in addition to the remedies otherwise available to a Party, at law or in equity.

These Terms shall not restrict the Receiving Party from complying with any legal requirement to disclose Confidential Information, provided that the Receiving Party shall to the extent that it is not prohibited from doing so by applicable law, promptly notify the Disclosing Party of such legal requirement so that the Disclosing Party may seek to quash such order and to obtain a protective order requiring that the relevant Confidential Information be held in confidence by such court or agency or, if disclosed, be used only for the purposes for which the order was issued. The Receiving Party shall cooperate fully with the Disclosing Party in any such proceeding.

The confidentiality obligations enlisted hereinabove for the Platform shall survive for the term of this Agreement.
<br>
<strong>16. DATA PROTECTION</strong>
You shall comply with and take all reasonable care with respect to protecting personal data that you may receive in connection with its performance of this Agreement. You shall implement adequate security measures to protect personal data commensurate with such measures you have in place to protect personal data of your own employees, customers and suppliers, not disclosing such personal data to any third-party and complying with all applicable data privacy laws. 

The Platform shall collect, use, store or otherwise process any data, whether or not personal in nature, from data source available in the public and use it for the purpose of performing its obligations under this Agreement and for its internal business operations. 

You hereby represent and warrant that you have the requisite consent/permission under applicable law and policies to collect, store share or otherwise use, display or publish any data and information (including but not limited to personal data received from the end-customers and or any other third-party) (<strong>“Customer Data”</strong> ) in connection with Services and will keep the Platform, fully indemnified against any third-party claims arising out of or in relation to such Customer Data.
<br>
You shall promptly notify the Platform of any information security breaches or incidents that could impact the performance of either Party’s obligations under this Agreement. The Parties shall jointly determine the corrective action required to be taken in connection with such information security breach or incident.
<br>
<strong>AVAILABILITY AND ACCESSIBILITY OF THE PLATFORM</strong>
We control and operate the Platform from India and make no representation that the Platform and/or the materials and the content available on the Platform are appropriate to be used or will be available for use in other locations outside India. If you use the Platform from outside India, you agree that you chose to do so with a clear understanding that the Platform makes no representation regarding suitability, availability or compliance of the Platform with applicable laws, rules or requirements in your country or operation. 

<br>
<strong>18. COPYRIGHTS IN CONTENT</strong>
The Platform contains material, including text, graphics and sound, which is protected by copyright and/or other intellectual property rights (<strong>“Content”</strong> ). All copyright and other intellectual property rights in the Content are either owned by us or have been licensed to us by the owner(s) of those rights so that we can use the Content as part of Service. We retain copyright on all information, including text, graphics and sound and all trademarks displayed on the Platform are either owned by us or licensed to us.

You may print off one copy, and may download extracts, of any page(s) from the Platform for your personal reference and you may draw the attention of others within your organization to material available on the Platform.

You must not modify the paper or digital copies of any materials you have printed off or downloaded in any way, and you must not use any illustrations, photographs, video or audio sequences or any graphics separately from any accompanying text.

You must not use any part of the materials on the Platform for commercial purposes without obtaining a license to do so from us or our licensors.

You may use and display the Content on your personal computer only for your personal use subject to the grant of a limited, revocable, personal, non-exclusive and non-transferable license to you by us. 

You may not: (a) copy (whether by printing off onto paper, storing on disk, downloading or in any other way), distribute (including distributing copies), download, display, perform, reproduce, distribute, modify, edit, alter, enhance, broadcast or tamper within any way or otherwise use any Content contained on the Platform. These restrictions apply in relation to all or part of the Content available on the Platform; (b) copy and distribute the information on any other server, or modify or re-use text or graphics on this system or another system; (c) reproduce any part of the Content or sell or distribute the same for commercial gain nor shall it be modified or incorporated in any other work, publication or website, whether in hard copy or electronic format, including postings to any other web site; (d) remove any copyright, trademark or other intellectual property notices contained in the original material from any material copied or printed off from the Content or the Platform; or (e) link any other material to the Content displayed on the Platform, without our express written consent.

The license granted to you does not include a license for: (a) any use of the Platform, the Services and/or of Content other than as contemplated in these Terms of Use, (b) any use of data mining, robots, or similar data gathering and extraction tools to extract (whether once or many times) any parts of Content.

If you believe that your intellectual property rights have been used in a way that raises concerns of infringement, please write to us at maasa.ventures@gmail.com  
<br>
<strong>19 . LICENSE AND USE OF YOUR CONTENT</strong>
You grant to us a royalty-free, perpetual, irrevocable, non-exclusive right and license to adopt, publish, reproduce, disseminate, transmit, distribute, copy, use, create derivative works from, display worldwide, or act on any material posted by you on the Platform ( <strong>“User Content”</strong> ) for the purpose of providing Services under the Terms, without additional approval. We do not claim ownership of the User Content; however, we do require a license to such User Content. We may use our rights under this license to operate, provide, and promote the Services and to perform our obligations and exercise our rights under the Terms. You represent, warrant, and agree that you have all necessary rights in the User Content to grant this license. You irrevocably waive all moral rights you may have in the User Content in favour of the Platform and agree that this waiver may be invoked by anyone who obtains rights in the materials through us, including anyone to whom we may transfer or grant (including by way of license or sublicense) any rights in the User Content.
<br>
We do not pre-screen User Content and it is in our sole discretion to refuse or remove any User Content from any part of the Services, including if we determine in our sole discretion that the Products or services that you offer through the Services, or the User Content uploaded or posted to the Services, violates these Terms.

Submissions and unauthorised use of any materials contained on the Platform may violate copyright laws, trademark laws, the laws of privacy and publicity, certain communications statutes and regulations and other applicable laws and regulations. You alone are responsible for your actions or the actions of any person using your username and/or password. 
<br>
<strong>20. INDEMNIFICATION AND LIMITATION OF LIABILITY</strong>
You agree to indemnify, defend and hold harmless us, our affiliates, officers, directors, employees, consultants, licensors, agents, and representatives from and against any and all third- party claims, losses, liabilities, damages, and/or costs (including reasonable attorney fees and costs) arising from (a) your access to or use of the Platform or the Content or the Services; (b) violation or breach of these Terms or the documents it incorporates herein by reference; (c) any acts of fraud, negligence or intentional misconduct by you ; (d) infringement of any of Platform’s Proprietary Rights or any third-party intellectual property or other rights; (e) breach of Seller Representations, Warranties, Covenants, obligations as per the Terms; and (f) breach of applicable law.  You will be responsible for any breach of the Terms by your affiliates, agents or subcontractors and will be liable as if it were your own breach.
<br>
We will notify you promptly of any such claim, loss, liability, or demand, and in addition to the foregoing, you agree to provide us with reasonable assistance, at your expense, in defending any such claim, loss, liability, damage, or cost.

Notwithstanding any other provision of this Agreement, the maximum aggregate liability of the Platform under this Agreement shall not exceed for an amount of Rs.5000/-.
<br>
<strong>21. DISPUTE RESOLUTION, GOVERNING LAW AND JURISDICTION</strong>
All disputes under this Agreement that have not been resolved as set forth above shall be resolved by E-Arbitration to be conducted by a sole arbitrator, who shall be jointly appointed by the Parties from the panel of available e-arbitrators.

This Agreement shall be governed by the laws of India and, subject to the arbitration process above, the Parties agree to submit to the exclusive jurisdiction of competent courts at Mumbai, India.


<br>
<strong>21 . CUSTOMER CARE SUPPORT</strong>
In accordance with the applicable law, any concern, feedback, you may write to us on maasa.ventures@gmail.com
<br>
<strong>22 . FORCE MAJEURE </strong>
We will not be held responsible for any delay or failure to comply with its obligations if the delay or failure arises from any cause which is beyond our reasonable control.
<br>
<strong>24 . WAIVER</strong>
No provision in these Terms will be deemed waived and no breach excused, unless such waiver or consent is in writing and signed by us. Any consent by us to, or waiver of your breach, whether expressed or implied, will not constitute consent to, waiver of, or excuse for any other different or subsequent breach.
<br>
<strong>24 . SEVERABILITY</strong>
If any provision of these Terms is held by a court of competent jurisdiction to be unenforceable under applicable law, then such provision will be excluded from these Terms and the remainder of these Terms will be interpreted as if such provision were so excluded and will be enforceable in accordance with its terms; provided however that, in such event, these Terms will be interpreted so as to give effect, to the greatest extent consistent with and permitted by applicable law, to the meaning and intention of the excluded provision as determined by such court of competent jurisdiction.
<br>
<strong>26 . NON-EXCLUSIVITY</strong>
Both the Parties agree that this Agreement is entered into on a non-exclusive basis and that both Parties shall be free to engage any third-party as its client/service provider to procure/provide similar or identical Services. 

***

            </article>
        </div>
    </section>
@endsection


